CREATE TABLE IF NOT EXISTS `feedback` (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `SITIN_RECORD_ID` int(11) NOT NULL,
    `STUDENT_ID` varchar(50) NOT NULL,
    `RATING` int(1) NOT NULL,
    `COMMENT` text,
    `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`),
    KEY `SITIN_RECORD_ID` (`SITIN_RECORD_ID`),
    CONSTRAINT `feedback_ibfk_1` FOREIGN KEY (`SITIN_RECORD_ID`) REFERENCES `sitin_records` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 